language: php

php:
 - 5.5

branches:
 only:
  - master

before_script:
 - composer self-update
 - composer install --dev --verbose
 - composer update

script:
 - cd tests
 - pwd
 - php ../vendor/phpunit/phpunit/phpunit --bootstrap bootstrap.php integration/GetLocationsTest.php
 - php ../vendor/phpunit/phpunit/phpunit --bootstrap bootstrap.php integration/GetPositionTest.php
 - php ../vendor/phpunit/phpunit/phpunit --bootstrap bootstrap.php integration/SetPositionTest.php

